[package]
name = "NeuroDEX"
version = "1.0.0"
authors = ["NeuroDEX Team"]

[addresses]
neurodex = "_"
std = "0x1"
aptos_framework = "0x1"
aptos_std = "0x1"

[dev-addresses]
neurodex = "0x42"

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dependencies.AptosStdlib]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-stdlib"

[dependencies.MoveStdlib]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/move-stdlib"
